feat: support for Quilt Mappings
zlataovce/takenaka pull request #33
Opened 2023-12-14 20:26 UTC by macbrayne

Adds support for intermediary based Quilt Mappings, this does not add support for hashed Quilt Mappings

2023-12-15 12:08 UTC, zlataovce requested changes

2023-12-15 12:08 UTC, zlataovce commented on core/src/main/kotlin/me/kcra/takenaka/core/mapping/resolve/impl/QuiltMappingResolver.kt
> +            var urlString = "https://maven.quiltmc.org/repository/release/org/quiltmc/quilt-mappings/$targetBuild/quilt-mappings-$targetBuild-intermediary-mergedv2.jar"
Quilt seems to do better than Fabric and has mergedv2 for all of their versions, so we can simplify this to just non-intermediary mergedv2 (and a no classifier artifact as a fallback, which seems to be the same as mergedv2 for some reason?)

2023-12-15 12:08 UTC, zlataovce commented on core/src/main/kotlin/me/kcra/takenaka/core/mapping/resolve/impl/QuiltMappingResolver.kt
> +            if (visitor0 is MappingTree) {
this block can be removed after simplification to mergedv2, since we don't need to merge ourselves

2023-12-16 17:59 UTC, macbrayne commented on core/src/main/kotlin/me/kcra/takenaka/core/mapping/resolve/impl/QuiltMetadataProvider.kt
> +            val buildString = versionNode.asText()
Done 👍

2023-12-16 18:13 UTC, zlataovce reviewed
I think Hashed can be excluded from ancestry/history namespaces in the Gradle plugin and the CLI by default, since it provides virtually no benefit in improving the cross-version matching accuracy - Intermediary already covers Quilt's version subset and is the same or has negligible differences accuracy wise.

2023-12-16 19:03 UTC, macbrayne commented
I'll remove Hashed from there then. Two things I had missed: namespaceFriendlinessIndex & historyNamespaces. I'll add Hashed after Intermediary for the first one, I'm not quite sure what the second one does though. Is Hashed relevant there?

2023-12-16 21:07 UTC, zlataovce commented
the friendliness index is used when selecting a "friendly" name - the namespaces are iterated in order and the first available name is used, that's the one you see in the documentation links, overview, package overview, ...

the history (ancestry) namespaces are used for following a trail of an element (class or a member) through multiple namespaces, i.e. when one namespace stops mapping an element, but another one still does, the elements can still be connected to maintain the ancestry line

2023-12-17 07:30 UTC, zlataovce approved these changes

2023-12-17 07:31 UTC, merged